<?php if (isset($errors['nickname'])): ?>
  <div class="text-danger"><?= $errors['nickname'] ?></div>
<?php endif ?>
<input
  type="text"
  class="form-control mb-3"
  placeholder="Никнейм"
  name="user[nickname]"
  id="nickname"
  require
  <?php if(isset($user['nickname'])): ?>
  value="<?= htmlspecialchars($user['nickname']) ?>"
  <?php endif; ?>
/>
<?php if (isset($errors['email'])): ?>
  <div class="text-danger"><?= $errors['email'] ?></div>
<?php endif ?>
<input
  type="email"
  class="form-control mb-3"
  placeholder="Email"
  name="user[email]"
  id="email"
  require
  <?php if(isset($user['email'])): ?>
  value="<?= htmlspecialchars($user['email']) ?>"
  <?php endif; ?>
/>