<div class="row">
  <div class="col-md-8 offset-md-2">
    <form 
      action="/users/<?= htmlspecialchars($user['id']) ?>" 
      method="post" 
      class="mt-3 card d-flex flex-column p-3"
    >
      <input type="hidden" name="_METHOD" value="PATCH">
      <?php require("_form.phtml") ?>
      <button class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2 d-flex">
    <a class="link-primary mt-3" href="/users">Ко всем пользователям</a>
  </div>
</div>