<?php foreach ($flash as $messages): ?>
  <?php foreach ($messages as $message): ?>
    <p><?= $message ?></p>
  <?php endforeach; ?>
<?php endforeach; ?>
<form method="GET" action="users">
  <div>
    <label>
      <input type="search" name="str" value="<?= htmlspecialchars($str) ?>">
    </label>
  </div>
  <div>
    <label>
      <input type="submit" value="Поиск">
    </label>
  </div>
</form>
<div>
<a href='/users/new'>Создать нового пользователя</a>
</div>
<div>
  <?php if (!empty($users)): ?>
  <ul>
    <?php foreach ($users as $user): ?>
    <li><?= htmlspecialchars($user['nickname']) ?></li>
    <?php endforeach; ?>
  </ul>
  <?php endif; ?>
</div>