<?php foreach ($flash as $key => $messages): ?>
    <?php foreach ($messages as $message): ?>
      <div class="alert alert-<?= htmlspecialchars($key) ?>">
        <?= htmlspecialchars($message) ?>
      </div>
    <?php endforeach; ?>
<?php endforeach; ?>
<div class="row">
  <div class="col">
    <form method="GET" action="users" class="d-flex justify-content-aroud">
      <input
        type="search"
        id="search"
        name="str"
        placeholder="Поиск по пользователям"
        value="<?= htmlspecialchars($str) ?>"
        class="form-control"
      />
      <button type="submit" class="btn btn-primary ms-3">Найти</button>
    </form>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <a href="/users/new" class="btn btn-primary w-100">Создать нового пользователя</a>
  </div>
</div>
<div class="row">
  <div class="col">
    <?php if (!empty($users)): ?>
    <ul class="list-group mt-3">
      <?php foreach ($users as $user): ?>
      <li class="list-group-item d-flex justify-content-between align-items-center">
          <a 
            href="/users/<?= htmlspecialchars($user['id']) ?>" 
            class="link-primary"
          >
          <?= htmlspecialchars($user['nickname']) ?>
        </a>
        <form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
          <input type="hidden" name="_METHOD" value="DELETE">
          <button class="btn btn-danger" type="submit">&times;</button>
        </form>
      </li>
      <?php endforeach; ?>
    </ul>
    <?php endif; ?>
  </div>
</div>
