<div class="row">
  <div class="col-md-8 offset-md-2">
    <form action="/users" method="post" class="mt-3 card d-flex flex-column p-3">
       <?php require("_form.phtml") ?>
       <button class="btn btn-primary">Создать</button>
    </form>
  </div>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2 d-flex">
    <a class="link-primary mt-3" href="/users">Ко всем пользователям</a>
  </div>
</div>