<table class="table table-striped table-bordered">
  <?php foreach($user as $key => $value): ?>
    <tr>
      <td>
        <?= htmlspecialchars($key) ?>
      </td>
      <td>
        <?= htmlspecialchars($value) ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
<div class="row">
  <div class="col">
    <a href="/users/<?= htmlspecialchars($user['id']) ?>/edit" title="Изменить пользователя">Изменить данные</a>
  </div>
  <div class="col">
    <a href="/users">
      Все пользователи
    </a>
  </div>
</div>